/***********************************************************************/
/*                                                                     */
/*  FILE        :interrupt_handlers.c                                  */
/*  DATE        :Thu, Jan 16, 2025                                     */
/*  DESCRIPTION :Interrupt Handler                                     */
/*  CPU TYPE    :Other                                                 */
/*                                                                     */
/*  This file is generated by KPIT GNU Project Generator.              */
/*                                                                     */
/***********************************************************************/
     




#include "interrupt_handlers.h"

// 2 Manual Reset PC
void INT_Manual_Reset_PC(void){  }
// 3 Manual Reset SP
void INT_Manual_Reset_SP(void){  }

// 4 Illegal code
void INT_Illegal_code(void){  }

// Dummy
void Dummy(void){  }
