/***********************************************************************/
/*                                                                     */
/*  FILE        :TEST2.c                                               */
/*  DATE        :Thu, Jan 16, 2025                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :Other                                                 */
/*                                                                     */
/*  This file is generated by KPIT GNU Project Generator.              */
/*                                                                     */
/***********************************************************************/
         
																							
																							
#include "vars.h"


#define BASE_FUEL_AIR_RATIO			0.07196f

void initFlexFuelCalcs(void) __attribute__ ((section ("RomHole_ForCode")));
void runFlexFuelCalcs(void) __attribute__ ((section ("RomHole_ForCode")));
void getFlexMetrics(void) __attribute__ ((section ("RomHole_ForCode")));
void calcTimingAdders(void) __attribute__ ((section ("RomHole_ForCode")));
void applyTimingAdders(void) __attribute__ ((section ("RomHole_ForCode")));
float func(void) __attribute__ ((section ("RomHole_ForCode")));

const float ethanol_content_sample_thresh_rpm __attribute__ ((section ("RomHole_calibrations"))) = 3100.0f;
const float ethanol_content_sample_thresh_load __attribute__ ((section ("RomHole_calibrations"))) = 0.5f;


unsigned short i = 0;


//TODO: These need to not be random RAM vars
float fuel_air_ratio __attribute__ ((section ("RAMHole_forVariables"))) = 0.0f;
float timing_mult  __attribute__ ((section ("RAMHole_forVariables"))) = 0.0f;
float timing_adder_trailing  __attribute__ ((section ("RAMHole_forVariables"))) = 0.0f;
float timing_adder_leading  __attribute__ ((section ("RAMHole_forVariables"))) = 0.0f;

//Setup patches for new adder pointers 
long timing_adder_trailing_ptr  __attribute__ ((section ("beans"))) = &timing_adder_trailing;
long timing_adder_leading_ptr __attribute__ ((section ("beans2")))  = &timing_adder_leading;

float func(){
	
	initFlexFuelCalcs();
	
	while(1){

		i=i+1;

		if(i >= 255 && i < 256){
			i=0;
		}
		
		runFlexFuelCalcs();
	}
	
	return 0;
	
}



void runFlexFuelCalcs(){
	
	getFlexMetrics();
	calcTimingAdders();
	applyTimingAdders();
	
}


void initFlexFuelCalcs(){
	
	fuel_air_ratio = BASE_FUEL_AIR_RATIO;
	timing_mult = 0.0f;
	timing_adder_trailing = 0.0f;
	timing_adder_leading = 0.0f;
	
}

void getFlexMetrics(){
	
	//if((*engine_speed_rpm > ethanol_content_sample_thresh_rpm) || (*engine_load_g_rev > ethanol_content_sample_thresh_load)){
		//Do not update fueling or timing variables
	//}else{
		fuel_air_ratio = Lookup2d(&ethanol_content_to_fuel_air_ratio_table_2d,*ethanol_content_pcnt);
		timing_mult = Lookup2d(&ethanol_content_to_timing_mult,*ethanol_content_pcnt);
	//}
	

		
}


void calcTimingAdders(){
	
	//Trailing
	timing_adder_trailing = Lookup3d(*engine_load_g_rev,*engine_speed_rpm,&timing_ethanol_adder_trailing);
	timing_adder_trailing = timing_adder_trailing * timing_mult;
		
	//Leading
	timing_adder_leading = Lookup3d(*engine_load_g_rev,*engine_speed_rpm,&timing_ethanol_adder_leading);
	timing_adder_leading = timing_adder_leading * timing_mult;
	
}

void applyTimingAdders(){
	
	//For Testing
	float local_leading_base_post =0.0f;
	float local_leading_base_pre = 0.0f;
	float local_trailing_base_post =0.0f;
	float local_trailing_base_pre = 0.0f;
	
	local_leading_base_pre = *ignition_leading_base_final_deg;
	calculateLeadingTimingBase();
	local_leading_base_post = *ignition_leading_base_final_deg;
	
	local_trailing_base_pre = *ignition_trailing_base_final_deg;
	calculateTrailingTimingBase();
	local_trailing_base_post = *ignition_trailing_base_final_deg;
	
}

void SetValues() __attribute__ ((section ("Misc")));

void SetValues() 
{
	// These are just here to clarify the boundary between the prologue and the
	// 'real' code when stepping through in a debugger.
	asm("nop");
	asm("nop");

	// If you change compiler settings, inspect the way the variables get set.
	// Ideally it should take three instructions per assignment, with no 
	// references to other memory.  If this does reference other memory, patches
	// will be difficult to apply.
	
	// LC/FFS test settings
	*engine_load_g_rev = 0.95f;
	*engine_speed_rpm = 6500.0f;
	*coolant_temp_degC = 1.0f;
	*ethanol_content_pcnt = 70.1f;
	*coolant_temp_post_fault_detection_degC = 85.0f;

}
