/***********************************************************************/
/*                                                                     */
/*  FILE        :vector_table.c                                        */
/*  DATE        :Thu, Jan 16, 2025                                     */
/*  DESCRIPTION :Vector Table                                          */
/*  CPU TYPE    :Other                                                 */
/*                                                                     */
/*  This file is generated by KPIT GNU Project Generator.              */
/*                                                                     */
/***********************************************************************/
               



#include "interrupt_handlers.h"

typedef void (*fp) (void);
extern void PowerON_Reset (void);
extern void stack (void);

#define VECT_SECT          __attribute__ ((section (".vects")))

const void *HardwareVectors[] VECT_SECT  = {
//;<<VECTOR DATA PowerON_Reset  (POWER ON RESET)>>
//;0 Power On Reset PC
    	PowerON_Reset ,
//;<<VECTOR DATA END (POWER ON RESET)>>
// 1 Power On Reset SP
    (fp)stack,
//;<<VECTOR DATA PowerON_Reset  (MANUAL RESET)>>
//;2 Manual Reset PC
    INT_Manual_Reset_PC,
//;<<VECTOR DATA END (MANUAL RESET)>>
// 3 Manual Reset SP
    INT_Manual_Reset_SP,
// 4 Illegal code
     INT_Illegal_code,
// xx Reserved
    (fp)0
};


